# Generated by Django 5.0.2 on 2024-02-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Headline_Express', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subs_info',
            old_name='suns_name',
            new_name='subs_name',
        ),
    ]
