# Generated by Django 5.0.2 on 2024-02-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Headline_Express', '0002_rename_suns_name_subs_info_subs_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subs_info',
            old_name='subs_email',
            new_name='Email_Id',
        ),
        migrations.RenameField(
            model_name='subs_info',
            old_name='subs_name',
            new_name='Name',
        ),
    ]
