# Generated by Django 5.0.2 on 2024-02-20 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Headline_Express', '0004_news_rename_email_id_subs_info_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 7, 19, 35, 29702, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='news',
            name='news_department',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
