# Generated by Django 5.0.2 on 2024-02-20 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Headline_Express', '0005_news_news_date_news_news_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_cat',
            new_name='news_name',
        ),
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 7, 57, 35, 63685, tzinfo=datetime.timezone.utc)),
        ),
    ]
