# Generated by Django 5.0.2 on 2024-02-20 08:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Headline_Express', '0008_news_news_department_alter_news_news_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='departments',
            new_name='department',
        ),
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=60, unique=True)),
                ('news_img', models.ImageField(upload_to='images/')),
                ('news_description', models.CharField(max_length=1000)),
                ('news_date', models.DateField(default=datetime.datetime(2024, 2, 21, 8, 21, 58, 756502, tzinfo=datetime.timezone.utc))),
                ('news_department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Headline_Express.department')),
            ],
        ),
        migrations.DeleteModel(
            name='news',
        ),
    ]
