# Generated by Django 5.0.2 on 2024-02-20 08:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Headline_Express', '0009_rename_departments_department_new_delete_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='department',
            new_name='departments',
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=60, unique=True)),
                ('news_img', models.ImageField(upload_to='images/')),
                ('news_description', models.CharField(max_length=1000)),
                ('news_date', models.DateField(default=datetime.datetime(2024, 2, 21, 8, 25, 11, 40677, tzinfo=datetime.timezone.utc))),
                ('news_department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Headline_Express.departments')),
            ],
        ),
        migrations.DeleteModel(
            name='new',
        ),
    ]
