# Generated by Django 5.0.2 on 2024-02-20 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Headline_Express', '0010_rename_department_departments_news_delete_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 8, 28, 26, 545617, tzinfo=datetime.timezone.utc)),
        ),
    ]
