# Generated by Django 5.0.2 on 2024-02-20 08:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Headline_Express', '0011_alter_news_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='department_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_dep', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 8, 47, 30, 587797, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='departments',
            name='main_dep',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Headline_Express.department_cat'),
        ),
    ]
