# Generated by Django 5.0.2 on 2024-02-20 09:11

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Headline_Express', '0012_department_cat_alter_news_news_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 9, 11, 12, 312497, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
