# Generated by Django 5.0.2 on 2024-02-21 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Headline_Express', '0013_alter_news_news_date_alter_news_news_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_department',
            new_name='dept_name',
        ),
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 22, 9, 58, 36, 607404, tzinfo=datetime.timezone.utc)),
        ),
    ]
