# Generated by Django 5.0.2 on 2024-02-22 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Headline_Express', '0014_rename_news_department_news_dept_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department_cat',
            name='main_desc',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department_cat',
            name='main_image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 23, 9, 48, 55, 63215, tzinfo=datetime.timezone.utc)),
        ),
    ]
