# Generated by Django 5.0.2 on 2024-02-22 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Headline_Express', '0015_department_cat_main_desc_department_cat_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 23, 10, 31, 47, 512990, tzinfo=datetime.timezone.utc)),
        ),
    ]
